### ISSUE TITLE
Use cloud-portal from docker-compose: Login error

### ISSUE THREAD

**Issue by SergeFocus** [chrisipa/cloud-portal#2]
use docker-compose.yml

``` 
mongodb:
  image: mongo:3.4.10
  volumes:
   - /srv/docker/cloud-portal/data:/data/db

tomcat:
  image: chrisipa/cloud-portal:latest
  links: 
  - mongodb
  environment:    
  - TOMCAT_SESSION_TIMEOUT=720
  - application.title=Cloud Portal
  - application.admin.group=my-admin-group
  - encryptor.secret=my-encryptor-secret
  - ldap.base.dn=dc=example,dc=com
  - ldap.group.attribute=memberOf
  - ldap.login.attribute=userPrincipalName
  - ldap.password=password
  - ldap.principal=cn=m y-admin-user,ou=users,dc=example,dc=com
  - ldap.url.string=ldap://192.168.0.62:389
  - ldap.user.search.filter=
  - mail.from=my-admin-user@gmail.com
  - mail.host=smtp.gmail.com
  - mail.send=true
  - spring.data.mongodb.uri=mongodb://mongodb:27017/cloud-portal
  volumes:
  - /srv/docker/cloud-portal/logs:/opt/tomcat/log
  ports:
   - "80:8080"
   - "443:8443"
```

Where my-admin-user@gmail.com - Login E-mail, 
           password - Password

LDAP server - working

```
{'groups': [('cn=my-admin-group,dc=example,dc=com',
             {'cn': ['my-admin-group'],
              'description': ['my-admin-group'],
              'gidNumber': ['1'],
              'objectClass': ['posixGroup', 'top']})],
 'orgs': [('ou=Cloud Portal,dc=example,dc=com',
           {'description': ['Cloud Portal'],
            'objectClass': ['organizationalUnit', 'top'],
            'ou': ['Cloud Portal']}),
          ('ou=users,dc=example,dc=com',
           {'description': ['users'],
            'objectClass': ['organizationalUnit', 'top'],
            'ou': ['users']})],
 'users': [('cn=m y-admin-user,ou=users,dc=example,dc=com',
            {'cn': ['m y-admin-user'],
             'gidNumber': ['1'],
             'givenName': ['m'],
             'homeDirectory': ['/home/my-admin-user'],
             'initials': ['m.y.'],
             'loginShell': ['/bin/bash'],
             'mail': ['my-admin-user@gmail.com'],
             'objectClass': ['inetOrgPerson', 'posixAccount', 'top'],
             'sn': ['y-admin-user'],
             'uid': ['my-admin-user'],
             'uidNumber': ['1002'],
             'userPassword': ['{SSHA}K7D/LX91DPJnIn+EHTCHsOpo+b0RUipL']})]}
```

/cloud-portal/login?error

here is my mistake?
