### ISSUE TITLE
Add support for ansible playbooks for bootstrapping

### ISSUE THREAD

**Issue by chrisipa** [chrisipa/cloud-portal#43]

**Comment by chrisipa** [comment]
Here's an example for executing ansible for Windows host machines:
```
ansible -i 192.168.0.1, -e ansible_user='ccc' -e ansible_password='P@ssword' -e ansible_port='5985' -e ansible_connection='winrm' -e ansible_winrm_server_cert_validation=ignore -e validate_certs=false 192.168.0.1 -m win_ping
```
And here's how to execute an ansible playbook:
```
ansible-playbook -i 192.168.0.1, -e ansible_user='ccc' -e ansible_password='P@ssword' -e ansible_port='5985' -e ansible_connection='winrm' -e ansible_winrm_server_cert_validation='ignore' -e validate_certs='false' windows.yml
```
And here's the ansible playbook file to install google chrome:
```
- hosts: all
  tasks:
  - name: Install google chrome package
    win_chocolatey:
      name: googlechrome
      state: present
```
